---
- name: Install and configure New Relic agent and its dependencies
  hosts: all
  gather_facts: true

  roles:
    - role: newrelic.newrelic-infra
      become: true
      vars:
        nrinfragent_state: 'latest'
        nrinfragent_config:
          license_key: "{{ new_relic['api_key'] }}"
          metrics_storage_sample_rate: 150
          metrics_process_sample_rate: 150
          metrics_network_sample_rate: 150
          metrics_system_sample_rate: 150
          metrics_nfs_sample_rate: 150
          enable_process_metrics: false
