---
- name: SSH server security best practices
  hosts: all
  gather_facts: true

  tasks:
    - name: Copy devops SSH keys
      ansible.builtin.copy:
        src: ../path_to_your/public_keys.txt
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        mode: "0644"

    - name: Configure SSH daemon
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "^(#)?{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
        state: present
      loop:
        - {key: "PermitRootLogin", value: "no"}
        - {key: "PasswordAuthentication", value: "no"}
        - {key: "AuthenticationMethods", value: "publickey"}
      notify:
        - Restart sshd

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      notify:
        - Restart sshd
      become: true
