---
- name: Get nginx worker count
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Read nginx.conf file
      shell: cat /etc/nginx/nginx.conf
      register: nginx_conf_contents

    - name: Extract worker_connections value
      set_fact:
        worker_connections: "{{ nginx_conf_contents.stdout | regex_findall('\\bworker_connections\\s+(\\d+);') | first }}"

    - name: Print worker_connections value
      debug:
        var: worker_connections
